version: '3.4'
services:
  voapi:
    image: voapi/voapi:latest
    ports: ["3000:3000"]
    environment:
      - SQL_DSN=root:password@tcp(mysql:3306)/voapi
      - REDIS_CONN_STRING=redis://redis:6379
      - SESSION_SECRET=your_random_string
  redis:
    image: redis:latest
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: voapi
